### ISSUE TITLE
YAY!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m3-evaluacion-intermedia-neired#1]
Buen trabajo @neired  !

Tres pistas para dejarlo más que fetén:

- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Usa propTypes para comprobar el tipo de dato de las props
- [x] Publica en Github Pages

Cuando tengas esto puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón

**Comment by neired** [comment]
Holi,
Creo que ya está :)
En estilos quería hacer algo más currado, pero me he liado intentando poner una estrellita de fontawesome y al final lo he dejado sólo con un cambio de clase... Pero bueno, funcionar funciona! Marca y desmarca!
Te diré que cuando se han empezado a añadir pokemons al array de favoritos se me ha saltado una lagrimita...
Hasta el lunes!

**Comment by oneeyedman** [comment]
Muy buen trabajo!
